---
- hosts: all
  become: true
  pre_tasks:

  - name:  Update Repo cache (Centos)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Centos"

  - name: Update Repo cache (Ubuntu)
    tags: always
    apt:
       update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: Add SSH key for mgelvoleo
    tags: always
    authorized_key:
      user: mgelvoleo
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKvhJYVSTiIeWlO9KG8YMP38P9vKbdU82cGax2jq8T1I ansible"
  

- hosts: webservers
  become: true
  tasks:

  - name: Install apache and php for Ubuntu Package
    tags: apache, apache2, ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"


  - name: Install apache2 and php for Centos Package
    tags: apache, centos, httpd
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Start httpd (CentOS)
    tags: centos, httpd, apache
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: Sample Copy html file for site
    tags: apache, apache2, httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
  
  - name: Rename the email of the admin for apache
    tags: apache, ubuntu, httpd
    lineinfile:
      path: /etc/apache2/apache2.conf
      regexp: '^#ServerRoot'
      line: "ServerName www.srv.world"
    when: ansible_distribution == "Ubuntu"
    register: apache2

  - name: Restart Apache (Ubuntu)
    tags: apache, ubuntu, httpd
    service:
      name: apache2
      state: reload
    when:  apache2.changed

  
- hosts: dbservers
  become: true
  tasks:

  - name: Install MariaDB for Centos Package
    tags: centos, db, mariadb
    dnf:
      name: mariadb  
      state: latest
    when: ansible_distribution == "CentOS"
 
  - name: Install MariaDB for Ubuntu  Package
    tags: db, mariadb, ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: fileservers
  become: true
  tasks:

  - name: Install Samba Package
    tags: samba
    package:
      name: samba 
      state: latest
    
