---
- hosts: all
  become: true
  tasks:

  - name: Update Repository Index
    apt:
      update_cache: yes

  - name: Uninstall apache2 package
    apt:
      name: apache2
      state: absent

  - name: Uninstall PHP support for apache
    apt: 
      name: libapache2-mod-php
      state: absent
