---
- name: Example Ansible playbook for Handlers
  hosts: all
  become: yes
  remote_user: mgelvoleo
  roles:
    - custom-role

  vars:
    # 1. String Variable
    main_playbook_variable: "foo"

    is_enabled: true

    fruits:
      - apple
      - banana
      - orange

    fruit_prices:
      apple: 0.5
      banana: 0.25
      orange: 0.75

    
    

  tasks:
   - name: Display
     debug:
       var: fruit_prices[1]
   

   
    
    
    
    

    