---
- name: Example Ansible playbook for Handlers
  hosts: all
  become: yes
  remote_user: ubuntu
  roles:
    - custom-role

  vars:
    # 1. String Variable
    main_playbook_variable: "foo"

    

  tasks:
    - name: String Variable from - main_playbook_variable
      debug:
        var: main_playbook_variable 
    
    
    

    