---
- name: Example Ansible playbook for Handlers
  hosts: all
  become: yes
  remote_user: mgelvoleo
  roles:
    - custom-role

  vars:
    # 1. String Variable
    main_playbook_variable: "foo"

    # 2. Boolean Variable
    is_enabled: true

    # 3. List Variable
    language:
      - python
      - java
      - perl

    language_version:
      python: 0.5
      java: 0.25
      perl: 0.75
    
    

  tasks:
   - name: String Variable from - main_playbook_variable
     debug:
       var: main_playbook_variable

   - name: Boolean variable
     debug:
       msg: "Variable is true"
     when: is_enabled

   - name: List variable - Print list of fruits
     debug:
       var: fruit

   - name: List variable - Reference individual item in list
     debug:
       var: fruits[0]
   
    
    
    
    

    