---
- name: Example Ansible playbook for Handlers
  hosts: all
  become: yes
  remote_user: mgelvoleo
  roles:
    - custom-role

  vars:
    # 1. String Variable
    main_playbook_variable: "foo"

    # 2. Boolean Variable
    is_enabled: true

    # 3. List Variable
    fruits:
      - apple
      - banana
      - orange

    fruit_prices:
      apple: 0.5
      banana: 0.25
      orange: 0.75
    
    

  tasks:
   - name: String Variable from - main_playbook_variable
     debug:
       var: main_playbook_variable

   - name: Boolean variable
     debug:
       msg: "Variable is true"
     when: is_enabled

   - name: List variable - Print list of fruits
     debug:
       var: fruits

   - name: List variable - Reference individual item in list
     debug:
       var: fruits[0]
   
    
    
    
    

    