---
- name: Example Ansible playbook for Handlers
  hosts: all
  become: yes
  remote_user: mgelvoleo
  roles:
    - custom-role

  vars:
    # 1. String Variable
    main_playbook_variable: "foo"

    is_enabled: true

    fruits:
      - apple
      - banana
      - orange

    
    

  tasks:
   - name: Display
     debug:
       var: fruits
   

   
    
    
    
    

    