---
- name: Example Ansible playbook for Handlers
  hosts: all
  become: yes
  remote_user: mgelvoleo
  roles:
    - custom-role

  vars:
    # 1. String Variable
    main_playbook_variable: "foo"

    is_enabled: false

    
    

  tasks:
   - name: String Variable from - main_playbook_variable
     debug:
       msg: "Variable is true"
     when: is_enabled
   

   
    
    
    
    

    