---
- name: Example Ansible playbook for Handlers
  hosts: all
  become: yes
  remote_user: ubuntu
  roles:
    - custom-role

  vars:
    # 1. String Variable
    main_playbook_variable: "foo"

    

  tasks:
    - name: String Variable from - main_playbook_variable
      debug:
        var: main_playbook_variable 
      tags:
        - string_var
    
    - name: Boolean variable
      debug:
        msg: "Variable is true"
      when: is_enabled
      tags:
        - boolean_var

    - name: List variable - Print list of computer language
      debug:
        var: language
      tags:
        - list_var

    - name: List variable - Reference individual item in listd
      debug:
       var: language_version[0]
      tags:
        - individual_item 

    - name: Dictionary Variable - Accessing individual specific fields
      debug:
        var: language_version.python

    - name: Get the value of apple from the nested variable
      debug:
        var: fruit_prices[fruit_basket[0].fruits[0]]

    # Jinja 2 filter on variables
    - name: Using Jinja 2 filters on variables
      debug:
        var: fruit_prices.keys() | list | map('upper') | list

    # Accessing variable inside playbook from my-vars.yml
    - name: Get the value of variable from my-vars.yml
      debug:
        var: vars_from_my_vars_yml

    #Defining and accessing the variable at RunTime
    - name: Get the value from run time
      debug:
        var: version

    #Defining and accessing the variable at RunTime
    - name: Print the value of variable when var file is passed at run time
      debug:
        var: other_variable

    