---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Create deployment directory
  file:
    path: /var/www/{{ deployment_color }}
    state: directory

- name: Deploy index.html
  template:
    src: templates/index.html.j2
    dest: /var/www/{{ deployment_color }}/index.html
  notify:
    - Reload Nginx